CREATE DATABASE COVID19
USE COVID19

------CAU_a--------
CREATE TABLE CA_NN
(
MaCa CHAR(5) NOT NULL,
HoVaTen NVARCHAR(50) NOT NULL,
NgaySinh DATE NOT NULL,
GioiTinh BIT,
DC NVARCHAR(100) NOT NULL
PRIMARY KEY(MaCa)
)

CREATE TABLE TRIEU_CHUNG
(
MaTC CHAR(10) NOT NULL,
MoTa NVARCHAR(50) NOT NULL,
TrongSo INT CHECK (TrongSo >=1 AND TrongSo <=100)
PRIMARY KEY(MaTC)
)


CREATE TABLE CA_TC
(
MaCa CHAR(5) NOT NULL,
MaTC CHAR(10) NOT NULL,
MucDo FLOAT CHECK(MucDo >=1 AND MucDo <=10)
PRIMARY KEY (MaCa,MaTC)
CONSTRAINT FK_CA_TC_MaCa FOREIGN KEY(MaCa) REFERENCES CA_NN(MaCa),
CONSTRAINT FK_CA_TC_MaTC FOREIGN KEY(MaTC) REFERENCES TRIEU_CHUNG(MaTC)
)

CREATE TABLE TEST
(
MaTest CHAR(5) NOT NULL,
TenTest NVARCHAR(50) NOT NULL,
NhaSX NVARCHAR(50),
FalsePositive CHAR(10) CHECK(FalsePositive >=0 AND FalsePositive<=100),
FalseNegative CHAR(10) CHECK(FalseNegative>=0 AND FalseNegative<=100)
PRIMARY KEY (MaTest)
)

CREATE TABLE CA_TEST
(
MaCa CHAR(5),
MaTest CHAR(5),
NgayTest DATE NOT NULL,
KetQua INT CHECK(KetQua = N'1' OR KetQua = N'0')
PRIMARY KEY (MaCa,MaTest)
CONSTRAINT FK_CA_TEST_MaCa FOREIGN KEY(MaCa) REFERENCES CA_NN(MaCa),
CONSTRAINT FK_CA_TEST_MaTest FOREIGN KEY(MaTest) REFERENCES TEST(MaTest)
)

------CAU_b------------------
INSERT INTO TRIEU_CHUNG(MaTC,MoTa,TrongSo)
VALUES(N'001',N'mất khứu giác',N'45');

INSERT INTO CA_NN(MaCa,HoVaTen,NgaySinh,GioiTinh,DC)
VALUES(N'0A1',N'TEPKANNITHA',N'2000-12-21',N'1',N'CAMPUCHIA');


-------CAU_c------------
SELECT HoVaTen,DC
FROM CA_NN
WHERE CA_NN.MaCa IN ( SELECT MaCa FROM CA_TEST WHERE NgayTest <'2022-01-14')
AND GioiTinh = N'1'


------cau_E-------
SELECT COUNT(MaCa) AS TONGSOKetQua
FROM CA_TEST
WHERE KetQua = N'1'
GROUP BY NgayTest



------cau_F-------
SELECT HoVaTen, GioiTinh
FROM CA_NN
WHERE CA_NN.MaCa IN (SELECT MaCa FROM CA_TC WHERE MucDo BETWEEN '7.5' AND '10')


