CREATE DATABASE CAFEE
USE CAFEE


CREATE TABLE NHACUNGCAP
(
MANCC CHAR(5) NOT NULL,
TENNCC NVARCHAR(100) NOT NULL,
EMIAL NVARCHAR(30) NOT NULL,
SDT_NCC CHAR(12) NOT NULL,
LV_CUNGUNG NVARCHAR(20) NOT NULL,
DIACHI_NCC NVARCHAR(100) NOT NULL,
PRIMARY KEY (MANCC)
)


CREATE TABLE NHANVIEN
(
MANV CHAR(5) NOT NULL,
TENNV NVARCHAR(100) NOT NULL,
NGAYSINH DATETIME,
GIOITINH BIT,
EMAIL NVARCHAR(100) NOT NULL,
SDT_NV CHAR(15) NOT NULL,
NGAY_BD_LAM DATETIME,
DIACHI_NV NVARCHAR(100),
PRIMARY KEY (MANV)
)


CREATE TABLE PHIEUCHI
(
MAPC CHAR(10) NOT NULL,
MANV CHAR(5) NOT NULL,
NOIDUNGCHI NVARCHAR(MAX),
NGAYLAP DATETIME,
TONGTIEN FLOAT
PRIMARY KEY (MAPC)
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE PHIEUTHU
(
MAPHIEUTHU CHAR(10) NOT NULL,
MANV CHAR(5) NOT NULL,
NOIDUNGTHU NVARCHAR(MAX),
NGAYLAP DATETIME,
TONGTIEN FLOAT
PRIMARY KEY (MAPHIEUTHU)
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)


CREATE TABLE PHIEUNHAP
(
MAPN CHAR(10) NOT NULL,
MANV CHAR(5) NOT NULL,
MANCC CHAR(5) NOT NULL,
NGAYLAP DATETIME,
TONGTIEN FLOAT,
SOLUONG FLOAT,
DON_GIA FLOAT
PRIMARY KEY (MAPN)
CONSTRAINT FK_PHIEUNHAP_MANV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
)


CREATE TABLE HOADON
(
MAHD CHAR(50) NOT NULL,
MANV CHAR(5) NOT NULL,
NGAYLAP DATETIME,
TONGTIEN FLOAT,
STT CHAR(5) NOT NULL,
TENKH NVARCHAR (30),
SOLUONG CHAR(5) NOT NULL
PRIMARY KEY(MAHD)
CONSTRAINT FK_HOADON_MANV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
) 


CREATE TABLE NGUYENLIEU
(
MANL CHAR(10) NOT NULL,
TENNL NVARCHAR(100), 
PRIMARY KEY(MANL)
)


CREATE TABLE CHITIET_PHIEUNHAP
(
MANL CHAR(10) NOT NULL,
MAPN CHAR(10) NOT NULL,
SOLUONG FLOAT
PRIMARY KEY (MANL,MAPN)
CONSTRAINT FK_CHITIET_PHIEUNHAP_MANL FOREIGN KEY(MANL) REFERENCES NGUYENLIEU(MANL),
CONSTRAINT FK_CHITIET_PHIEUNHAP_MAPN FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN)
)


CREATE TABLE CHITIET_NCC(
MAPN CHAR(10) NOT NULL,
MANCC CHAR(5) NOT NULL
PRIMARY KEY (MAPN,MANCC)
CONSTRAINT FK_CHITIET_NCC_MAPN FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC),
CONSTRAINT FK_CHITIET_NCC_MANCC FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN)
)

CREATE TABLE CONG_THUC(
MACT CHAR(5) NOT NULL,
MATU CHAR(5) NOT NULL,
TEN_CT NVARCHAR(30)
PRIMARY KEY (MACT)
)





CREATE TABLE CHITIET_CONGTHUC
(
MACT CHAR(5) NOT NULL,
MANL CHAR(10) NOT NULL,
SOLUONG FLOAT,
DONVI_TINH NVARCHAR(25) NOT NULL
PRIMARY KEY (MACT,MANL)
CONSTRAINT FK_CHITIET_CONGTHUC_MACT FOREIGN KEY(MACT) REFERENCES CONG_THUC(MACT),
CONSTRAINT FK_CHITIET_CONGTHUC_MANL FOREIGN KEY(MANL) REFERENCES NGUYENLIEU(MANL)
)


CREATE TABLE CHAMCONG
(
MACC CHAR(5) NOT NULL,
TG_LAMVIEC TIME,
NGAY_NGHI DATETIME,
LUONG FLOAT,
MANV CHAR(5)
PRIMARY KEY(MACC)
CONSTRAINT FK_CHAMCONG_MANV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)


CREATE TABLE THUCUONG
(
MATU CHAR(5) NOT NULL,
TENTU NVARCHAR(100) NOT NULL,
MANL CHAR(10) NOT NULL,
SIZE CHAR(5),
DON_GIA FLOAT
PRIMARY KEY (MATU)
)

CREATE TABLE CHITIET_HOADON
(
MATU CHAR(5) NOT NULL,
MAHD CHAR(50) NOT NULL,
SOLUONG FLOAT
PRIMARY KEY(MATU,MAHD)
CONSTRAINT FK_CHITIET_HOADON_MATU FOREIGN KEY(MATU) REFERENCES THUCUONG(MATU),
CONSTRAINT FK_CHITIET_HOADON_MAHD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)
)

--thêm 1 cột tên TUOI vào bảng NHANVIEN 
ALTER TABLE NHANVIEN ADD TUOI CHAR(3);


--biểu diễn iều kiện lựa chọn 
--đưa ra dang sách các nhân viên có địa chỉ 'KY TUC XA t4'
SELECT*FROM NHANVIEN
WHERE (DIACHI_NV = 'KY TUC XA t4')

--biểu diễn iều kiện lựa chọn 
--thống kế nhũng phiếu nhập có tổng tiền <9000000
SELECT MAPC,NOIDUNGCHI,NGAYLAP,TONGTIEN AS 'TONG TIEN' 
FROM PHIEUCHI
WHERE (TONGTIEN<9000000)

--tìm kiếm sắp sếp theo thứ tự
--đưa ra danh sách tổng tiền của hóa đơn theo thứ tự tăng dần
SELECT MAHD,MANV,NGAYLAP,STT,TENKH AS 'TEN', TONGTIEN AS TOTAL
FROM HOADON
ORDER BY TONGTIEN ASC 
                                            
--đưa ra danh sách tổng tiền của hóa đơn theo thứ tự giảm dần 
SELECT MAHD,MANV,NGAYLAP,STT,TENKH AS 'TEN', TONGTIEN AS TOTAL
FROM HOADON
ORDER BY TONGTIEN DESC

--sắp xếp kết quả theo thứ tự (A-Z) cho tên của nhân viên
SELECT*FROM NHANVIEN ORDER BY TENNV;

--lấy các thông tin từ bảng PHIEUNHAP với điều kiện là TONGTIEN nhỏ hơn 2 triệu và DON_GIA lớn hơn 60000
SELECT*FROM PHIEUNHAP
WHERE TONGTIEN < 2000000 AND DON_GIA>60000;




